sudo: required

env:
  DOCKER_IMAGE=sfnagg/k8s-helm-logs

services:
  - docker

# Only build tags
if:
  tag IS present

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

script:
  - docker build -t $DOCKER_IMAGE .
  - docker tag $DOCKER_IMAGE:$TRAVIS_TAG $DOCKER_IMAGE:latest

after_success:
  - docker push $DOCKER_IMAGE:$TRAVIS_TAG
  - docker push $DOCKER_IMAGE:latest
