sudo: required

# Only build tags
if: 
  tag IS present

env:
  DOCKER_IMAGE=sfnagg/k8s-helm-logs

services:
  - docker

script:
  - docker build -t $DOCKER_IMAGE:$TRAVIS_TAG .
  - docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE:latest

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_IMAGE:$TRAVIS_TAG
  - docker push $DOCKER_IMAGE:latest
