sudo: required

env:
  DOCKER_IMAGE=sfnagg/k8s-helm-logs

services:
  - docker

if:
  branch = master OR tag IS present

before_script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

script:
  - export DOCKER_TAG=${TRAVIS_TAG}
  - docker build --no-cache -t ${DOCKER_IMAGE}:${DOCKER_TAG} .
  - docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKER_IMAGE}:latest

after_success:
  - docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
  - docker push ${DOCKER_IMAGE}:latest
